#title
title: Yzz
# Header
menu:
    home: /
    about : /about
    tags : /tags
    archives: /archives
# title
header:
    aboutHeader: About
    aboutData: Information
    aboutInformation: Social
    aboutTarget: Project
    aboutFriendlink: Talent
# author date
data:
    name: 杨挺or杨滋滋
    school: 本科/广东东软学院
    position: 前端工程师
# SubNav
subnav:
    gitHub: "https://github.com/yzzting"
    weiBo: "http://weibo.com/yzzting"
    zhiHu: "https://www.zhihu.com/people/yang-zi-zi-1995"
# Project
project:
    hexo主题: https://github.com/yzzting/hexo-theme-MyFairLady
# friendlink
friendlink:
    ahonn的博客: http://www.ahonn.me
    刘帆帆的博客: http://henbukexue.science

# read more
excerpt_link: read more

# favicon
favicon: http://7xp1k3.com1.z0.glb.clouddn.com/octocat-de-los-muertos.jpg

# Baidu Analytics
# baidu_analytics: c21994907883f37ffd80e13627dd4faa

# Google Analytics
google_analytics: UA-75314797-1
